version: 2
defaults: &defaults
  docker:
    - image: howdy39/st-node-nightmare
  working_directory: ~/my_working_directory

jobs:
  setup:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: dependencies-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/my_working_directory
          paths:
            - ./*

  release:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/my_working_directory
      - run:
          command: |
            mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
      - run: source scripts/build-tag.sh

  release-beta:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/my_working_directory
      - run:
          command: |
            mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
      - run: source scripts/release-beta.sh

workflows:
  version: 2
  setup-and-release:
    jobs:
      - setup
      - hold:
          type: approval
          requires:
            - setup
      - release:
          requires:
            - hold
      - release-beta:
          requires:
            - setup
          filters:
            branches:
              only: dashboard-renewal