version: 2
defaults: &defaults
  docker:
    - image: howdy39/st-node-nightmare
  working_directory: ~/my_working_directory

jobs:
  setup:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: dependencies-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/my_working_directory
          paths:
            - ./*

  buildtag:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/my_working_directory
      - add_ssh_keys:
          fingerprints:
            - "43:c1:a8:9d:35:cc:e4:1d:47:8b:7d:ea:b3:4c:60:bc"
      - run: source scripts/build-tag.sh

workflows:
  version: 2
  setup-test-and-deploy:
    jobs:
      - setup:
          filters:
            tags:
              only: /^v.*/
      - buildtag:
          requires:
            - setup
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
